### DISCUSSION TITLE
Esp32 possible?

### DISCUSSION THREAD

**Discussion by Delusional112** [adonno/tagreader#180] [Q&A]
Does it work with an ESP32 board?

greetings Danny

**Comment by JoeFromQA** [comment]
Did you ever find out?

**Reply by ChrisThomas42** [reply]
I have a tag reader working with a Seeed Studio Xiao ESP32 C3.  I copied the``` tagreader.yaml``` code and built the "new" code with changes to the board and the pin numbers, otherwise it's identical.  Only issue I had was finding a small buzzer to go into a small box.

I also have an original Adonno reader and the only real difference is the sound made in my build isn't as good.  Future improvement is to source a better buzzer!  I only use them as simple tag readers for an alarm, so the NFC card manipulation code is untested on the C3.

Having Adonno release an ESP32 version in a nice case would smarten up black box stuck on the wall and hopefully sound better!

**Comment by adonno** [comment]
It would require some changes or an additional file for ESP32
The yaml is especially for ESP8266

**Reply by Lifth1309** [reply]
Thanks for the clarification!
I was wondering about that too. Well, actually i wasn't - i assumed i could just simply replace the ESP8266 with an ESP32 and was searching for a STL-Casing-File. :) Your answer saved me from the inevitable disappointment. The idea was - since i'm going to place a couple of bluetooth-proxies around the house anyways - to get some tagreaders out of it as well.

**Comment by IAmTheFuzz1** [comment]
This is probably a relatively basic question, but I'm looking at this for my first dive into the ESP Home ecosystem. Wondering what changes/additional file I'd need for the ESP32 over ESP8266?
I've got a few projects in mind and I feel like using the one type of board will make my life easier. Feel free to say "don't be silly, use an ESP8266" :D

**Comment by teleoltre** [comment]
I was also thinking of using an esp32, as I have unstable wifi problems. I would like to replace 8266 with esp32+DevKitC-LAN8720 and then use the lan and maybe even the poe with the superior model.
What changes should be made?

**Comment by ChrisThomas42** [comment]
I made changes to the board and the pins to reflect the board I used, then replace the esp8266 definition with

```
esp32:
  board: ${board}
  framework:
    type: esp-idf
 ``` 

changed buzzer to
```
output:
- platform: ledc
  pin: ${buzzer}
  id: buzzer
```

and the LED to
```
light:
- platform: esp32_rmt_led_strip #neopixelbus
  chipset: ws2812
  pin: ${status_led}
  num_leds: 1
  rgb_order: GRB
  id: activity_led
  name: "Status LED"
  restore_mode: ALWAYS_OFF
```

I left the other code as is, if I remember rightly.
