### DISCUSSION TITLE
Several readers one NFC tag

### DISCUSSION THREAD

**Discussion by xxLexanixx** [adonno/tagreader#235] [Ideas]
I would like to use several readers for different speakers.

Example:
Tag1 is read on Reader1, so music should be played on Loudspeaker1.

Or

Tag1 is read on Reader2, so music should be played on Loudspeaker2.

For this I would have to be able to create the automation in such a way that it knows which day was read on which reader.

Would it be possible to tell me how I could implement this?

**Comment by ljarbinet** [comment]
Not sure you found a solution in the meantime but I'm looking for something similar

**Comment by seanmccabe** [comment]
I've got this, which I've used since day one, allows playing on different speakers depending on the reader that was used

```
- alias: "Handle Tag Scan"
  id: 1501e3cb-a732-482e-9b99-934fc3f4c886
  mode: queued
  # Hide warnings when triggered while in delay.
  max_exceeded: silent
  variables:
    # Map scanner device ID to media player entity ID
    media_players:
      #tagreader_3
      ad8b0518a45e46g4f723e0f07722a5ef1: media_player.****_speaker
      #tagreader_4
      56e42b8244a0agh63d74db02b6dc62aa: media_player.****_speaker
  trigger:
    platform: event
    event_type: tag_scanned
action:
    - variables:
      media_player_entity_id: "{{ media_players[trigger.event.data.device_id] }}"
 ```
