### DISCUSSION TITLE
ESP-WROOM-32 Configuration?

### DISCUSSION THREAD

**Discussion by geroulas** [adonno/tagreader#253] [Q&A]
Can you help with the changes in pinouts and yaml I need in order to do this with an ESP-WROOM-32?

**Comment by geroulas** [comment]
I managed to get it wotking by changing:

```
esphome:
  name: $name
  platform: esp32
  board: nodemcu-32s
```
and

```
output:
- platform: ledc
  pin: GPIO13
  id: buzzer
```
