### ISSUE TITLE
after ESP8266 restart HA settings "buzzer enabled" and "LED enabled" get reset

### ISSUE THREAD

**Issue by paulius2k** [adonno/tagreader#126]
I have settings "buzzer enabled" and "LED enabled" in my HA set to "true".
But after ESP8266 restart those settings get reset to "false".
Is there any way to set them permanently?

**Comment by nielsrune** [comment]
I have done it with an automation to avoid having to re-upload the code to the chip.
This is my automation for the buzzer only. Add LED if you want that too:
```
alias: Tagreader startup script
description: Set tagreader buzzer on when HA is started
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: binary_sensor.tagreader_status
    from: 'off'
    to: 'on'
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_on
    entity_id: switch.tagreader_buzzer_enabled
    domain: switch
mode: restart

```
