### ISSUE TITLE
Can't find a way... adding a swich to pin 5.

### ISSUE THREAD

**Issue by Erestes** [adonno/tagreader#197]
I would like to add a piece of config  that would allow connecting a switch to pin:5 but I keep failing...
I've added the following into the switch section:
`# Define the switch
- platform: gpio
  pin: 
    number: 5
    inverted: true
  name: "${friendly_name} Switch"`

What am I doing wrong?

**Comment by adonno** [comment]
```
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay
```
this part is to have the switch working. in your Case the pin is GIPO14 (CF image) 

![image](https://user-images.githubusercontent.com/13216947/199223542-e1a48145-f92a-42c3-8cad-17e480d6d3ef.png)


This adds a switch in the interface that react base on the `binary_sensor `

```
switch:
  - platform: gpio
    name: ${plug_name}_relay
    id: relay
    pin: GPIO12
```
