### ISSUE TITLE
override tagreader.yaml

### ISSUE THREAD

**Issue by mariomare22** [adonno/tagreader#208]
Hello!
is there a way I can override the ap directive in my tagreader.yaml from my esphome?
I would like to setup a password for the captive if no wifi is found.
```
# Insert your SSID and Your PWD after inital setup
wifi:
# networks:
#    - ssid: 'REPLACEME'          # Enter your WiFi SSID here. Example: `ssid: 'your_network_name'`
#      password: 'REPLACEME'      # Enter your wifi password here. Example: `password: 'abcde123456'`
  ap:
    ssid: ${name}
```

**Comment by adonno** [comment]
Hello Sorry for the late reply 

just add : 

```
wifi:
  ap:
    ssid: ${name}
    password: xxxxxxxx
```

that's all there is normally it should keep this info
