### ISSUE TITLE
Status LED

### ISSUE THREAD

**Issue by Marlor** [adonno/tagreader#38]
More like a heads up than a Bug or a FR

ESPHome can use the build in LED of the D1 Mini as [Status LED](https://esphome.io/components/status_led.html)
Blinking is somethings is wrong like no wifi / HA API / Sensor connection
Off is everything is ok

```
status_led:
  pin:
    number: D4
    inverted: True
```

Did help me alot debugging and now in everyday use
