### ISSUE TITLE
ESPHome tag_scanned events

### ISSUE THREAD

**Issue by jesserockz** [adonno/tagreader#6]
From 0.115.0 the Home Assistant ESPHome integration supports sending to the tag component directly.

home-assistant/core#40128
home-assistant/core#40130
home-assistant/core#40132

This will also be released as an action in ESPHome in a future release:

esphome/esphome#1281

```
pn532:
  ...
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'
```

Before that is released though in ESPHome, you can use:

```
pn532:
  ...
  on_tag:
    then:
      - homeassistant.event:
          event: esphome.tag_scanned
          data:
            tag_id: !lambda 'return x;'
```
