### ISSUE TITLE
RFID Card and NFC Phone | Inconsistent behaviour

### ISSUE THREAD

**Issue by CarpeDiemRo** [adonno/tagreader#76]
**Prerequisites**
a. Wemos D1 mini
b. PN RFID 532
c. Card & tag, 13.56 MHz
d. master branch pn532_i2c

**Use case** 
I want to use my Huawei Mate 20 Pro as an NFC Tag

**What I did**
1. Open Home Assistant Companion which is logged in at HA instance
2. NFC Tag option from Settings
3. Write Tag on White Card
4. Returning results
```
- platform: event
  event_type: tag_scanned
  event_data:
    device_id: 93d872ca49dfe4d7
    tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
```
5. Fire event button
6. Check if *ce1685b2-0bdf-4786-bea4-39caa49c4035* is displayed in Tags from configuration
![image](https://user-images.githubusercontent.com/38489167/99916706-585cba80-2d14-11eb-8311-242c2d3b78f0.png)

7. Make the following automation in automation.yaml

```
- alias: "Huawei NFC Access"
  initial_state: True
  mode: single
  trigger:
  - platform: event
    event_type: tag_scanned
    event_data:
      device_id: 93d872ca49dfe4d7
      tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
  action:
    - service: switch.toggle
      entity_id: switch.shelly_1pm
```
8. Reload automation
9. Swipe Huawei Phone

**Expected results**
1. The bulb must be switched on

**Actual results**
1. The bulb is not light on and a new entry is created in Tags
2. Huawei and White Card still have different identificators
![image](https://user-images.githubusercontent.com/38489167/99916727-762a1f80-2d14-11eb-961e-f3d7c14eebe9.png)

**More actions**
1. Go To events and listen *tag_scanned*
2. Scan Huawei and White Card
--> "device_id": `bf45cac435a56ede5256ea83fed4f9c0` is the same for both.
--> tag id is different than the id created with HA Companion
--> device_id is different than the id created with HA Companion
![image](https://user-images.githubusercontent.com/38489167/99916745-978b0b80-2d14-11eb-9574-73f453011060.png)
--
3. Go to automation and at device_id paste `bf45cac435a56ede5256ea83fed4f9c0` value

*New automation code excluded tag_id*
```
- alias: "Huawei NFC Access Device ID"
  initial_state: True
  mode: single
  trigger:
  - platform: event
    event_type: tag_scanned
    event_data:
      device_id: bf45cac435a56ede5256ea83fed4f9c0
    #   tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
  action:
    - service: switch.toggle
      entity_id: switch.shelly_1pm
```
4. Reload automation
5. Swipe White Card --> the bulb is switching ON
6. Swipe Huawei --> the bulb is switching ON
7. Check Tags from HA
New Tag is created for Huawei 
8. Swipe Huawei again
New Tag is created for Huawei
![image](https://user-images.githubusercontent.com/38489167/99916774-c5705000-2d14-11eb-88ed-edfc096d5f24.png)

**Expected results**
Huawei and White card should be considered one entity
When I write a new card 

```
      device_id: 93d872ca49dfe4d7
      tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
```
must be used in automation in order to make two entities to act as one

--
**More Testing**
1. Go To HA companion and read White Card
--> results

```
- platform: event
  event_type: tag_scanned
  event_data:
    device_id: 93d872ca49dfe4d7
    tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
```
2. Make the following automation

```
- alias: "Huawei NFC Access"
  initial_state: True
  mode: single
  trigger:
  - platform: event
    event_type: tag_scanned
    event_data:
      device_id: 93d872ca49dfe4d7
      tag_id: ce1685b2-0bdf-4786-bea4-39caa49c4035
  action:
    - service: switch.toggle
      entity_id: switch.shelly_1pm
```
3. Fire the event directly from the HA companion / Button **Fire Event**
--> The bulb is switching ON and OFF
--> Verify-in Tags if `ce1685b2-0bdf-4786-bea4-39caa49c4035` was used == yes
4. Swipe Huawei in order to obtain the same result
--> a new tag is created
--> the bulb remains switched off

**In conclusion**
if I used *Fire Event* button directly from HA companion the phone trigger the action and in TAGS is used the device id which was created, but if I put the **same** values in the automation I am not able to obtain the same behavior
